ci: fix create PR

diff --git a/.github/workflows/generate.yml b/.github/workflows/generate.yml
--- a/.github/workflows/generate.yml
+++ b/.github/workflows/generate.yml
@@ -166,7 +166,7 @@ jobs:
           PR_BRANCH="auto-update-openapi-merged-yaml"
           PR_TITLE="ChatGPT pluggin - update merged OpenAPI yaml file"
           PR_BODY="ChatGPT pluggin - update merged OpenAPI yaml file"
-          PR_LINK=`gh pr edit "$PR_BRANCH" -b "PR_BODY" -t "$PR_TITLE"  && gh pr reopen "$PR_BRANCH" || gh pr create --fill -B main -H "$PR_BRANCH"`
+          PR_LINK=`gh pr create --body "$PR_BODY" --title "chore: ChatGPT pluggin - update merged OpenAPI yaml file" || echo "Cannot create PR. Possibly PR already exists"`
           echo "::add-mask::$PR_LINK"
           echo "pr-link=$PR_LINK" >> "$GITHUB_OUTPUT"
 
