ci: action to create merged.yaml for ChatGPT plugin. (#142)

diff --git a/.github/workflows/generate.yml b/.github/workflows/generate.yml
--- a/.github/workflows/generate.yml
+++ b/.github/workflows/generate.yml
@@ -55,7 +55,7 @@ jobs:
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
-      
+
       - name: Checkout SDK repo
         uses: actions/checkout@v3
         with:
@@ -97,4 +97,74 @@ jobs:
           fi
         env:
           GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
-        
+
+  update_merged_yaml:
+    name: update merged yaml file
+    runs-on: ubuntu-latest
+    container:
+      image: python:3.9-alpine3.18
+    steps:
+      - name: install gh cli
+        run: |
+          apk add github-cli git
+
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: merge files
+        env:
+          TOKEN_REPO_INTEGRATION: ${{ secrets.TOKEN_REPO_INTEGRATION }}
+          TARGET_REPO: ${{ secrets.MERGER_REPO }}
+        run: |
+          OLD_PWD=`pwd`
+          TEMP_DIR=`mktemp -d`
+          cd $TEMP_DIR
+          git clone https://$TOKEN_REPO_INTEGRATION:x-oauth-basic@github.com/aziontech/$TARGET_REPO.git .
+          cd openapi
+          pip install -r ./requirements.txt
+          python processor.py $OLD_PWD/edgefunctions.yaml $OLD_PWD/idns.yaml
+          cp ./output/merged.yaml $OLD_PWD/openapi.yaml
+          cd $OLD_PWD
+      - name: create update PR
+        id: create-pull-request
+        env:
+          TOKEN_REPO_INTEGRATION: ${{ secrets.TOKEN_REPO_INTEGRATION }}
+          GH_TOKEN: ${{ secrets.TOKEN_REPO_INTEGRATION }}
+          TARGET_REPO: ${{ secrets.OPEN_API_MERGED_YAML_REPO}}
+          TARGET_MERGED_YAML_PATH: ${{ secrets.OPEN_API_MERGED_YAML_PATH }}
+        run: |
+          OLD_PWD=`pwd`
+          TEMP_DIR=`mktemp -d`
+          MERGED_YAML="$OLD_PWD/openapi.yaml"
+          cd $TEMP_DIR
+          git clone https://$TOKEN_REPO_INTEGRATION:x-oauth-basic@github.com/aziontech/$TARGET_REPO.git .
+          git checkout -b auto-update-openapi-merged-yaml
+          cp -f $MERGED_YAML $TARGET_MERGED_YAML_PATH
+          if [ -z "`git diff`" ]; then
+            echo "merged file was not changed"
+            exit 0
+          fi
+
+          git config user.name "Azion Github Automation"
+          git config user.email "github.automation@azion.com"
+
+          git add $TARGET_MERGED_YAML_PATH
+          git commit -m 'chore: ChatGPT pluggin - update merged OpenAPI yaml file'
+          git push --force origin auto-update-openapi-merged-yaml
+          PR_BRANCH="auto-update-openapi-merged-yaml"
+          PR_TITLE="ChatGPT pluggin - update merged OpenAPI yaml file"
+          PR_BODY="ChatGPT pluggin - update merged OpenAPI yaml file"
+          PR_LINK=`gh pr create --body "$PR_BODY" --title "chore: ChatGPT pluggin - update merged OpenAPI yaml file" || echo "Cannot create PR. Possibly PR already exists"`
+          echo "::add-mask::$PR_LINK"
+          echo "pr-link=$PR_LINK" >> "$GITHUB_OUTPUT"
+
+      - name: notify merged yaml update
+        if: false
+        # if: ${{ steps.create-pull-request.outputs.pr-link }} - TODO: add secret for slack_webhook
+        id: slack
+        uses: slackapi/slack-github-action@v1.24.0
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+        with:
+          payload: "${{ steps.create-pull-request.outputs.pr-link }}"
